### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by jkleinkopf** [zachary-foster/alignreads#11]
Hi Zachary,

I have been trying to figure out alignreads (and YASRA) to map reads to a reference made up of probe sequences. We want to keep the "splash zones" for our phylogenetic analyses, but have had trouble doing so in BWA. However, we keep getting errors with this program - first was the single-step error which we figured out quickly, but now we are getting the error 

> Traceback (most recent call last):
  File "/home/wade/Documents/alignreads/alignreads.py", line 467, in <module>
    reload(makeconsensus)
  File "/home/wade/Documents/alignreads/makeconsensus.py", line 207, in <module>
    pileups = list(readtools.PileupIO.parse(samPath, 'sam', applyPadding = False)) 
  File "/home/wade/Documents/alignreads/readtools.py", line 994, in parse
    for pileup in formatParsers[fileFormat](handleOrPath, applyPadding):
  File "/home/wade/Documents/alignreads/readtools.py", line 944, in readSam
    yield Pileup(alignments = pileupAlignments, padAlignments = applyPadding, name = pileupAlignments[0].reference)
IndexError: list index out of range

 Here is the run-time info from that run:

> === Run-time information ===
[2017-09-11 13:45:51,930]	DEBUG	alignreads	305	Validating input arguments...
[2017-09-11 13:45:51,930]	DEBUG	alignreads	320	Validating input arguments complete.
[2017-09-11 13:45:52,008]	DEBUG	alignreads	337	Checking for YASRA...
[2017-09-11 13:45:52,029]	DEBUG	alignreads	352	YASRA executable found at /home/wade/Documents/alignreads/bin.
[2017-09-11 13:45:52,030]	DEBUG	alignreads	356	Checking for lastz...
[2017-09-11 13:45:52,036]	DEBUG	alignreads	370	Version 1.03.02 of LASTZ found at /home/wade/Documents/alignreads/bin/lastz.
[2017-09-11 13:45:52,036]	DEBUG	alignreads	374	Checking for nucmer...
[2017-09-11 13:45:52,091]	DEBUG	alignreads	382	Version 3.1 of LASTZ found at /home/wade/Documents/alignreads/bin/nucmer.
[2017-09-11 13:45:52,091]	DEBUG	alignreads	388	Executing runyasra...
[2017-09-11 13:45:52,091]	INFO	alignreads	393	Implimenting YASRA with runyasra.py using the following command line:
 runyasra.py --percent-identity medium --lastz-binary-path /home/wade/Documents/alignreads/bin/lastz --yasra-binary-path /home/wade/Documents/alignreads/bin --read-type solexa --orientation linear --single-step --output-directory /media/wade/Files/Joseph/alignreadsPractice /media/wade/Files/Joseph/alignreadsPractice/CaffW_cleaned_concat.fa /media/wade/Files/Joseph/alignreadsPractice/blocks_for_probe_design_SINGLEREF.fasta
[2017-09-11 13:45:52,563]	DEBUG	runyasra	139	Creating the YASRA makefile...
[2017-09-11 13:45:52,563]	DEBUG	runyasra	325	YASRA makefile created.
[2017-09-11 13:45:59,080]	DEBUG	alignreads	409	Execution of runyasra complete...
[2017-09-11 13:45:59,081]	DEBUG	alignreads	431	Preparing output folder for post-yasra anaylsis....
[2017-09-11 13:45:59,082]	DEBUG	alignreads	453	Prepartion of output folder for post-yasra anaylsis complete.
[2017-09-11 13:45:59,082]	DEBUG	alignreads	457	Executing makeconsensus...
[2017-09-11 13:45:59,085]	CRITICAL	alignreads	469	An error occured during execution of makeconsensus.py:
[2017-09-11 13:45:59,085]	DEBUG	alignreads	477	Execution of makeconsensus complete.

We are having a bit of trouble figuring out where the program is having problems, but maybe something in YASRA is not working for us?

Thanks,
Joseph

**Comment by zachary-foster** [comment]
Sorry for the trouble @jkleinkopf! I will look into it and get back to you
